services:
  userservice:
    build:
      context: Services/userService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - user-db
  user-db:
    image: postgres:15
    environment:
        - POSTGRES_DB=users
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./.containers/user-db:/var/lib/postresql/data
    ports:
        - 5432:5432
      